import type { VisualBlock, BlockType } from '@/types/game';

export interface CompilerResult {
  success: boolean;
  blocks: VisualBlock[];
  logs: string[];
  error?: string;
  executionTimeMs: number;
}

/**
 * Creates unique ID for visual blocks generated by the compilers
 */
function uid(): string {
  return `blk_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
}

/**
 * Normalizes command names from both Python and JavaScript conventions
 */
function mapCommandToBlockType(cmd: string): BlockType | null {
  const clean = cmd.trim().toLowerCase().replace(/[();]/g, '');

  switch (clean) {
    case 'move_forward':
    case 'moveforward':
    case 'forward':
    case 'pet.move_forward':
    case 'pet.moveforward':
    case 'pet.forward':
      return 'move_forward';

    case 'move_back':
    case 'moveback':
    case 'back':
    case 'pet.move_back':
    case 'pet.moveback':
    case 'pet.back':
      return 'move_back';

    case 'move_right':
    case 'moveright':
    case 'right':
    case 'pet.move_right':
    case 'pet.moveright':
    case 'pet.right':
      return 'move_right';

    case 'move_left':
    case 'moveleft':
    case 'left':
    case 'pet.move_left':
    case 'pet.moveleft':
    case 'pet.left':
      return 'move_left';

    case 'move_up':
    case 'moveup':
    case 'up':
    case 'pet.move_up':
    case 'pet.moveup':
    case 'pet.up':
      return 'move_up';

    case 'move_down':
    case 'movedown':
    case 'down':
    case 'pet.move_down':
    case 'pet.movedown':
    case 'pet.down':
      return 'move_down';

    case 'turn_right':
    case 'turnright':
    case 'pet.turn_right':
    case 'pet.turnright':
      return 'turn_right';

    case 'turn_left':
    case 'turnleft':
    case 'pet.turn_left':
    case 'pet.turnleft':
      return 'turn_left';

    case 'interact':
    case 'collect':
    case 'pet.interact':
    case 'pet.collect':
      return 'interact';

    case 'jump':
    case 'pet.jump':
      return 'jump';

    default:
      return null;
  }
}

/**
 * In-browser Python Compiler & Interpreter for Petslyvia Academy
 * Supports:
 * - Direct commands: pet.move_right(), move_forward(), etc.
 * - Variables: steps = 8, count = 3
 * - For loops: for i in range(8):, for step in range(steps):
 * - While loops (with safety guard): while not pet.at_goal():
 * - Print statements: print("Hello from Python!")
 * - Indented block scoping
 */
export function compilePython(sourceCode: string): CompilerResult {
  const startTime = performance.now();
  const logs: string[] = ['🐍 Python 3.12 Virtual Runtime Initializing...'];
  const blocks: VisualBlock[] = [];
  const variables: Record<string, number> = {};

  try {
    const rawLines = sourceCode.split('\n');
    let lineNum = 0;

    interface ScopeContext {
      type: 'loop' | 'root';
      count: number;
      collectedBlocks: VisualBlock[];
      indent: number;
    }

    const scopeStack: ScopeContext[] = [{ type: 'root', count: 1, collectedBlocks: [], indent: -1 }];

    for (let i = 0; i < rawLines.length; i++) {
      lineNum = i + 1;
      const originalLine = rawLines[i];
      const trimmed = originalLine.trim();

      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }

      // Calculate indentation (spaces or tabs)
      const indentMatch = originalLine.match(/^(\s*)/);
      const currentIndent = indentMatch ? indentMatch[1].replace(/\t/g, '    ').length : 0;

      // Pop scopes if indent decreased
      while (
        scopeStack.length > 1 &&
        currentIndent <= scopeStack[scopeStack.length - 1].indent
      ) {
        const finishedScope = scopeStack.pop()!;
        const parentScope = scopeStack[scopeStack.length - 1];

        if (finishedScope.type === 'loop') {
          parentScope.collectedBlocks.push({
            id: uid(),
            type: 'repeat',
            params: { count: finishedScope.count },
            nestedBlocks: finishedScope.collectedBlocks,
          });
          logs.push(`[COMPILER] Closed for-loop (repeated ${finishedScope.count} times)`);
        }
      }

      const activeScope = scopeStack[scopeStack.length - 1];

      // Handle variable assignment: var = 5
      const varAssignMatch = trimmed.match(/^([a-zA-Z_]\w*)\s*=\s*(\d+)$/);
      if (varAssignMatch) {
        const varName = varAssignMatch[1];
        const val = parseInt(varAssignMatch[2], 10);
        variables[varName] = val;
        logs.push(`[ASSIGN] ${varName} = ${val}`);
        continue;
      }

      // Handle print statement
      const printMatch = trimmed.match(/^print\((.*)\)$/);
      if (printMatch) {
        const printVal = printMatch[1].replace(/^["']|["']$/g, '');
        logs.push(`[STDOUT] ${printVal}`);
        continue;
      }

      // Handle for loop: for <var> in range(<count>):
      const forRangeMatch = trimmed.match(/^for\s+(\w+)\s+in\s+range\(([^)]+)\)\s*:$/);
      if (forRangeMatch) {
        const rawCount = forRangeMatch[2].trim();
        let loopCount = parseInt(rawCount, 10);

        if (isNaN(loopCount) && rawCount in variables) {
          loopCount = variables[rawCount];
        }

        if (isNaN(loopCount) || loopCount < 1) {
          loopCount = 1;
        }
        // Safety cap loop count to 20
        loopCount = Math.min(loopCount, 20);

        scopeStack.push({
          type: 'loop',
          count: loopCount,
          collectedBlocks: [],
          indent: currentIndent,
        });

        logs.push(`[COMPILER] Opened loop: repeat ${loopCount} times`);
        continue;
      }

      // Handle while loop: while not pet.at_goal():
      const whileMatch = trimmed.match(/^while\s+(.+)\s*:$/);
      if (whileMatch) {
        // Approximate safety bounded loop
        scopeStack.push({
          type: 'loop',
          count: 5,
          collectedBlocks: [],
          indent: currentIndent,
        });
        logs.push(`[COMPILER] Opened guarded while loop: bounded to 5 iterations`);
        continue;
      }

      // Check standard pet action
      const blockType = mapCommandToBlockType(trimmed);
      if (blockType) {
        const newBlock: VisualBlock = { id: uid(), type: blockType };
        activeScope.collectedBlocks.push(newBlock);
        logs.push(`[ACTION] ${blockType}() queued`);
        continue;
      }

      // Unrecognized statement warning
      logs.push(`[WARN] Line ${lineNum}: Unrecognized command "${trimmed}". Skipping.`);
    }

    // Flush remaining open scopes
    while (scopeStack.length > 1) {
      const finishedScope = scopeStack.pop()!;
      const parentScope = scopeStack[scopeStack.length - 1];

      if (finishedScope.type === 'loop') {
        parentScope.collectedBlocks.push({
          id: uid(),
          type: 'repeat',
          params: { count: finishedScope.count },
          nestedBlocks: finishedScope.collectedBlocks,
        });
      }
    }

    const finalBlocks = scopeStack[0].collectedBlocks;
    const executionTimeMs = Math.round((performance.now() - startTime) * 100) / 100;

    if (finalBlocks.length === 0) {
      return {
        success: false,
        blocks: [],
        logs: [...logs, '⚠️ Error: No executable pet commands were generated from your code.'],
        error: 'No executable actions found. Try adding `pet.move_right()` or a `for` loop!',
        executionTimeMs,
      };
    }

    logs.push(`✓ Compilation complete. ${finalBlocks.length} instructions ready in ${executionTimeMs}ms.`);

    return {
      success: true,
      blocks: finalBlocks,
      logs,
      executionTimeMs,
    };
  } catch (err: any) {
    const executionTimeMs = Math.round((performance.now() - startTime) * 100) / 100;
    return {
      success: false,
      blocks: [],
      logs: [...logs, `❌ Python Compiler Error: ${err?.message || String(err)}`],
      error: err?.message || 'Syntax or evaluation error in Python code.',
      executionTimeMs,
    };
  }
}

/**
 * In-browser JavaScript Compiler & Sandbox Runtime for Petslyvia Academy
 * Supports:
 * - pet.moveForward(), pet.moveRight(), etc.
 * - Standard for loops: for (let i = 0; i < 8; i++) { pet.moveRight(); }
 * - Variables: let steps = 8;
 * - console.log(...)
 * - Functions: function walk() { ... }
 */
export function compileJavaScript(sourceCode: string): CompilerResult {
  const startTime = performance.now();
  const logs: string[] = ['⚡ Node.js v20 Sandbox Initializing...'];
  const generatedBlocks: VisualBlock[] = [];

  // Safe mock pet object passed into the sandbox
  const petMock = {
    moveForward: () => {
      generatedBlocks.push({ id: uid(), type: 'move_forward' });
      logs.push('[STDOUT] pet.moveForward()');
    },
    moveBack: () => {
      generatedBlocks.push({ id: uid(), type: 'move_back' });
      logs.push('[STDOUT] pet.moveBack()');
    },
    moveRight: () => {
      generatedBlocks.push({ id: uid(), type: 'move_right' });
      logs.push('[STDOUT] pet.moveRight()');
    },
    moveLeft: () => {
      generatedBlocks.push({ id: uid(), type: 'move_left' });
      logs.push('[STDOUT] pet.moveLeft()');
    },
    moveUp: () => {
      generatedBlocks.push({ id: uid(), type: 'move_up' });
      logs.push('[STDOUT] pet.moveUp()');
    },
    moveDown: () => {
      generatedBlocks.push({ id: uid(), type: 'move_down' });
      logs.push('[STDOUT] pet.moveDown()');
    },
    turnRight: () => {
      generatedBlocks.push({ id: uid(), type: 'turn_right' });
      logs.push('[STDOUT] pet.turnRight()');
    },
    turnLeft: () => {
      generatedBlocks.push({ id: uid(), type: 'turn_left' });
      logs.push('[STDOUT] pet.turnLeft()');
    },
    interact: () => {
      generatedBlocks.push({ id: uid(), type: 'interact' });
      logs.push('[STDOUT] pet.interact()');
    },
    collect: () => {
      generatedBlocks.push({ id: uid(), type: 'interact' });
      logs.push('[STDOUT] pet.collect()');
    },
    jump: () => {
      generatedBlocks.push({ id: uid(), type: 'jump' });
      logs.push('[STDOUT] pet.jump()');
    },
  };

  // Mock console
  const consoleMock = {
    log: (...args: any[]) => {
      logs.push(`[LOG] ${args.map(a => typeof a === 'object' ? JSON.stringify(a) : String(a)).join(' ')}`);
    },
    warn: (...args: any[]) => {
      logs.push(`[WARN] ${args.join(' ')}`);
    },
    error: (...args: any[]) => {
      logs.push(`[ERR] ${args.join(' ')}`);
    },
  };

  try {
    // Also provide snake_case globals
    const move_forward = petMock.moveForward;
    const move_right = petMock.moveRight;
    const move_left = petMock.moveLeft;
    const move_back = petMock.moveBack;
    const move_up = petMock.moveUp;
    const move_down = petMock.moveDown;
    const turn_right = petMock.turnRight;
    const turn_left = petMock.turnLeft;

    // Safety wrapper to execute within sandboxed Function
    const sandboxFn = new Function(
      'pet',
      'console',
      'move_forward',
      'move_right',
      'move_left',
      'move_back',
      'move_up',
      'move_down',
      'turn_right',
      'turn_left',
      `"use strict";\n${sourceCode}`
    );

    sandboxFn(
      petMock,
      consoleMock,
      move_forward,
      move_right,
      move_left,
      move_back,
      move_up,
      move_down,
      turn_right,
      turn_left
    );

    const executionTimeMs = Math.round((performance.now() - startTime) * 100) / 100;

    if (generatedBlocks.length === 0) {
      return {
        success: false,
        blocks: [],
        logs: [...logs, '⚠️ Warning: No pet actions were triggered by your JavaScript code.'],
        error: 'No movements occurred. Did you call `pet.moveRight()` or `move_forward()`?',
        executionTimeMs,
      };
    }

    // Safety limit to 50 blocks
    const finalBlocks = generatedBlocks.slice(0, 50);
    logs.push(`✓ JavaScript execution complete. ${finalBlocks.length} actions executed in ${executionTimeMs}ms.`);

    return {
      success: true,
      blocks: finalBlocks,
      logs,
      executionTimeMs,
    };
  } catch (err: any) {
    const executionTimeMs = Math.round((performance.now() - startTime) * 100) / 100;
    return {
      success: false,
      blocks: [],
      logs: [...logs, `❌ Runtime Error: ${err?.message || String(err)}`],
      error: err?.message || 'JavaScript runtime evaluation error.',
      executionTimeMs,
    };
  }
}
